name: Continuous Integration
on: push
env:
  cache-version: v1

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node }}
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM cache
        uses: actions/cache@v2.0.0
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          resore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
